# See https://owncast.online/docs/configuration/ for more details
ffmpegPath: ./ffmpeg-mac
webServerPort: 8080
rtmpServerPort: 1935

instanceDetails:
  name: DeluCast Test
  title: DeluCast Test
  summary: "This is a test of the emergency broadcasting system"

  logo: /img/logo.svg

  tags:
    - music
    - software
    - streaming

  # https://owncast.online/docs/configuration/#external-links
  # for full list of supported social links.  All optional.
  socialHandles:
    - platform: github
      url: http://github.com/owncast/owncast

videoSettings:
  # Change this value and keep it secure.  Treat it like a password to your live stream.
  streamingKey: faog84hskel48dhe0ake6dl3haijxn45

  streamQualities:
    - medium:
      videoBitrate: 1200
      encoderPreset: veryfast

# Set to true if you don't want the service checking for future releases.
disableUpgradeChecks: false

# Off by default.  You can optionally list yourself in the Owncast directory.
# Make sure your instanceURL is the public URL to your Owncast instance.
yp:
  enabled: false
  instanceURL: https://stream.myserver.org